function renderDash(){
  var cfg=getCfg();
  var finReady = typeof _finIncome!=='undefined' && typeof _finExpense!=='undefined' && typeof _finSubscriptions!=='undefined' && typeof _finAssets!=='undefined' && typeof _finMonthlySettings!=='undefined';
  if(typeof loadKPI==='function') loadKPI();
  if(finReady && typeof _syncPayrollExpenses==='function') _syncPayrollExpenses();
  var totalEval=evalHistory.length,totalPay=payHistory.length,totalEmp=employees.length;
  var activeEmp=employees.filter(function(e){ return e.statusAktif!==false; }).length;
  var avgScore=totalEval?evalHistory.reduce(function(a,b){return a+(parseFloat(b.fs)||0);},0)/totalEval:0;
  var totalGaji=payHistory.reduce(function(a,b){return a+_num(b.bersih);},0);
  var thisMonth=new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0');
  var latestKPI=(kpiData.filter(function(d){return d.periode===thisMonth;})[0]||{data:{}});
  var monthlyRows=(finReady && typeof _finBuildMonthlySummary==='function'?_finBuildMonthlySummary():[]);
  var currentMonth=monthlyRows.filter(function(r){ return r.key===thisMonth; })[0]||monthlyRows[monthlyRows.length-1]||{name:'-',penjualan:0,pengeluaran:0,saldo:0,laba:0,cash:0,targetPenjualan:0,progressPenjualan:0,cashGoal:0,cashProgress:0,hutangSupplier:0,marketplaces:[],rowCount:0};
  var bestMonth=monthlyRows.slice().sort(function(a,b){return b.saldo-a.saldo;})[0]||currentMonth;
  var avgProfitMonthly=(finReady && typeof _finAverageProfitMonthly==='function'?_finAverageProfitMonthly():0);
  var projectedExpense=(finReady && typeof _finProjectedExpenseMonthly==='function'?_finProjectedExpenseMonthly():0);
  var expenseRatio=avgProfitMonthly>0?(projectedExpense/avgProfitMonthly*100):0;
  var supplierRows=(typeof supplierHutang!=='undefined'?supplierHutang:[]);
  var supplierSummary={};
  var totalNota=0,totalBayar=0,totalSaldoSupplier=0;
  supplierRows.forEach(function(d){
    var nm=(d.namaSupplier||'Golden Fish').trim()||'Golden Fish';
    var nota=(d.nota||[]).reduce(function(t,n){return t+(parseFloat(n.nilaiNetto)||0);},0);
    var bayar=(d.bayar||[]).reduce(function(t,b){return t+(parseFloat(b.jumlah)||0);},0);
    totalNota+=nota; totalBayar+=bayar; totalSaldoSupplier+=(nota-bayar);
    supplierSummary[nm]=supplierSummary[nm]||{nota:0,bayar:0,saldo:0,count:0};
    supplierSummary[nm].nota+=nota; supplierSummary[nm].bayar+=bayar; supplierSummary[nm].saldo+=(nota-bayar); supplierSummary[nm].count+=1;
  });
  var supplierTop=Object.keys(supplierSummary).map(function(nm){ return {nama:nm,saldo:supplierSummary[nm].saldo,nota:supplierSummary[nm].nota,bayar:supplierSummary[nm].bayar,count:supplierSummary[nm].count}; }).sort(function(a,b){return b.saldo-a.saldo;}).slice(0,3);
  var reminders=(finReady && typeof _finSubscriptionReminders==='function'?_finSubscriptionReminders():[]).filter(function(r){ return r.level==='overdue'||r.level==='today'||r.level==='soon'; }).slice(0,4);
  var hrDiscipline=(typeof _hrControlData!=='undefined' && _hrControlData && Array.isArray(_hrControlData.disciplineLog)?_hrControlData.disciplineLog:[]);
  var hrWarnCount=hrDiscipline.filter(function(r){ return ['Evaluasi','SP1','SP2','PHK Review','PHK'].indexOf(String(r.stage||''))>=0; }).length;
  var sopCount=(typeof _hrSops!=='undefined' && Array.isArray(_hrSops)?_hrSops.length:0);
  var evalThisMonth=evalHistory.filter(function(r){ return String(r.submittedAt||r.ts||'').slice(0,7)===thisMonth; }).length;
  var payrollThisMonthRows=payHistory.filter(function(r){ return String(r.submittedAt||r.ts||'').slice(0,7)===thisMonth; });
  var payrollThisMonth=payrollThisMonthRows.reduce(function(sum,r){ return sum+_num(r.bersih); },0);
  var toolsRefund7=(typeof _toolRefunds!=='undefined' && typeof _toolsFilterRange==='function')?_toolsFilterRange(_toolRefunds,'7d').length:0;
  var toolsComplaint7=(typeof _toolComplaints!=='undefined' && typeof _toolsFilterRange==='function')?_toolsFilterRange(_toolComplaints,'7d').length:0;
  var toolsRequestOpen=(typeof _toolRequests!=='undefined' ? _toolRequests.filter(function(r){ return String(r.status||'').toLowerCase()!=='done'; }).length : 0);
  var recentLogs=[];
  evalHistory.slice(0,3).forEach(function(r){ recentLogs.push({ts:r.submittedAt||r.ts||'', type:'Penilaian', title:(r.info&&r.info.nama)||'-', meta:'Nilai '+((r.fs||0).toFixed?r.fs.toFixed(2):r.fs)}); });
  payHistory.slice(0,3).forEach(function(r){ recentLogs.push({ts:r.submittedAt||r.ts||'', type:'Payroll', title:(r.info&&r.info.nama)||'-', meta:'Rp '+fmt(r.bersih||0)}); });
  if(finReady) _finIncome.slice(-4).forEach(function(r){ var m=_finIncomeMetrics(r); recentLogs.push({ts:r.ts||'', type:'Pendapatan', title:m.toko||m.marketplace||'-', meta:'Laba Rp '+fmt(m.keuntunganKerugian||0)}); });
  if(finReady) _finExpense.slice(-4).forEach(function(r){ recentLogs.push({ts:r.ts||'', type:'Pengeluaran', title:_finExpenseLabel(r), meta:'Rp '+fmt(r.nominal||0)}); });
  recentLogs.sort(function(a,b){ return String(b.ts||'').localeCompare(String(a.ts||'')); });
  var hasWA=!!(cfg.adminWA),hasTg=!!(cfg.tgToken&&cfg.tgChat),hasDrv=!!(cfg.driveToken),hasSB=!!(cfg.supabaseUrl&&cfg.supabaseKey);
  var h='';
  h+='<div class="card" style="padding:12px 14px;margin-bottom:12px;background:linear-gradient(135deg,rgba(240,197,106,.1),rgba(143,208,255,.05))"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><div style="font-size:16px;font-weight:800;color:#F0C56A">Dashboard AJW</div><div style="font-size:11px;color:var(--tx2);margin-top:4px">Pantauan ringkas HR, Finance, Tools, supplier, dan integrasi penting.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><span class="chip" style="border:1px solid rgba(240,197,106,.28);background:rgba(240,197,106,.07);color:#F0C56A">Fokus '+esc(currentMonth.name)+'</span><span class="chip" style="border:1px solid rgba(143,208,255,.25);background:rgba(143,208,255,.07);color:#8FD0FF">'+esc(cfg.adminName||'Hokky')+'</span></div></div></div>';
  h+='<div style="display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:10px;margin-bottom:12px">';
  [['Karyawan Aktif',activeEmp,'#8FD0FF',evalThisMonth+' evaluasi bulan ini'],['Payroll Bulan Ini','Rp '+fmt(payrollThisMonth),'#A7F3B6',payrollThisMonthRows.length+' slip'],['Penjualan','Rp '+fmt(currentMonth.penjualan),'#F0C56A',currentMonth.rowCount+' data masuk'],['Saldo Bersih','Rp '+fmt(currentMonth.saldo||0),(currentMonth.saldo||0)>=0?'#A7F3B6':'#FF9D9D','Bulan aktif'],['Komplain 7 Hari',toolsComplaint7,'#FFB76B',toolsRefund7+' refund • '+toolsRequestOpen+' request'],['Hutang Supplier','Rp '+fmt(totalSaldoSupplier||0),'#FFD68A',Object.keys(supplierSummary).length+' supplier']].forEach(function(card){
    h+='<div class="card" style="margin-bottom:0;background:var(--bg3);padding:12px;position:relative;overflow:hidden"><div style="position:absolute;top:0;left:0;right:0;height:2px;background:'+card[2]+'"></div><div style="font-size:10px;font-weight:700;color:'+card[2]+';text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px">'+card[0]+'</div><div style="font-size:20px;font-weight:800;color:var(--tx)">'+card[1]+'</div><div style="font-size:10px;color:var(--tx2);margin-top:5px;line-height:1.45">'+card[3]+'</div></div>';
  });
  h+='</div>';
  h+='<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;align-items:start;margin-bottom:12px">';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><div style="font-size:13px;font-weight:800;color:var(--tx)">Pantauan HR</div><button class="btns" onclick="_navTo(\'hr\')" style="width:auto">Buka HR</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px">'+[['Evaluasi',evalThisMonth],['Payroll',payrollThisMonthRows.length],['Log Control',hrWarnCount],['SOP',sopCount]].map(function(x){ return '<div style=\"background:var(--bg3);border:1px solid var(--bd);border-radius:8px;padding:10px\"><div style=\"font-size:10px;color:var(--tx2);text-transform:uppercase\">'+x[0]+'</div><div style=\"font-size:18px;font-weight:800;color:var(--tx);margin-top:4px\">'+x[1]+'</div></div>'; }).join('')+'</div><div style="grid-column:1 / -1;font-size:11px;color:var(--tx2);line-height:1.7;padding-top:8px">Avg nilai: <b style="color:var(--tx)">'+(avgScore>0?avgScore.toFixed(2):'-')+'</b> • Payroll total: <b style="color:var(--tx)">Rp '+fmt(totalGaji)+'</b></div></div>';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><div style="font-size:13px;font-weight:800;color:var(--tx)">Pantauan Finance</div><button class="btns" onclick="_navTo(\'finance\')" style="width:auto">Buka Finance</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-bottom:8px">'+[['Cash Bank','Rp '+fmt(currentMonth.cash),'#F0C56A'],['Pengeluaran','Rp '+fmt(currentMonth.pengeluaran),'#FFB76B'],['Laba','Rp '+fmt(currentMonth.laba||0),(currentMonth.laba||0)>=0?'#A7F3B6':'#FF9D9D'],['Rasio',avgProfitMonthly>0?expenseRatio.toFixed(1)+'%':'-',(expenseRatio<=85?'#8FD0FF':'#FFD68A')]].map(function(x){ return '<div style=\"background:var(--bg3);border:1px solid var(--bd);border-radius:8px;padding:10px\"><div style=\"font-size:10px;color:'+x[2]+';text-transform:uppercase;font-weight:700\">'+x[0]+'</div><div style=\"font-size:18px;font-weight:800;color:var(--tx);margin-top:4px\">'+x[1]+'</div></div>'; }).join('')+'</div><div style="font-size:11px;color:var(--tx2);line-height:1.7">Target: <b style="color:var(--tx)">'+(currentMonth.progressPenjualan*100).toFixed(1)+'%</b> • Bulan terbaik: <b style="color:var(--tx)">'+esc(bestMonth.name||'-')+'</b></div></div>';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><div style="font-size:13px;font-weight:800;color:var(--tx)">Tools & Integrasi</div><button class="btns" onclick="_navTo(\'tools\')" style="width:auto">Buka Tools</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-bottom:8px">'+[['Refund 7H',toolsRefund7],['Komplain 7H',toolsComplaint7],['Request Aktif',toolsRequestOpen],['Reminder',reminders.length]].map(function(x){ return '<div style=\"background:var(--bg3);border:1px solid var(--bd);border-radius:8px;padding:10px\"><div style=\"font-size:10px;color:var(--tx2);text-transform:uppercase\">'+x[0]+'</div><div style=\"font-size:18px;font-weight:800;color:var(--tx);margin-top:4px\">'+x[1]+'</div></div>'; }).join('')+'</div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px">'+[['WA',hasWA,'#25D366'],['Supabase',hasSB,'#6EE7B7'],['Telegram',hasTg,'#0088CC'],['Drive',hasDrv,'#0F9D58']].map(function(x){ return '<div style=\"background:var(--bg3);border:1px solid '+(x[1]?x[2]+'44':'var(--bd)')+';border-radius:8px;padding:9px 10px\"><div style=\"font-size:10px;font-weight:700;color:'+(x[1]?x[2]:'var(--tx3)')+'\">'+x[0]+'</div><div style=\"font-size:10px;color:var(--tx2);margin-top:3px\">'+(x[1]?'Aktif':'Belum')+'</div></div>'; }).join('')+'</div></div>';
  h+='</div>';
  h+='<div style="display:grid;grid-template-columns:minmax(0,1.15fr) minmax(280px,.85fr);gap:12px;align-items:start;margin-bottom:12px">';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px"><div style="font-size:13px;font-weight:800;color:var(--tx)">Aktivitas Terbaru</div><button class="btns" onclick="_navTo(\'finance\');setTimeout(function(){_renderFinance(\'income\')},60)" style="width:auto">Pendapatan</button></div><div style="overflow-x:auto"><table class="tbl" style="min-width:720px"><thead><tr><th>Waktu</th><th>Tipe</th><th>Item</th><th>Keterangan</th></tr></thead><tbody>';
  recentLogs.slice(0,8).forEach(function(r){
    h+='<tr><td style="white-space:nowrap;color:var(--tx2)">'+esc(r.ts?new Date(r.ts).toLocaleString('id-ID'):'-')+'</td><td>'+esc(r.type)+'</td><td style="font-weight:700">'+esc(r.title||'-')+'</td><td>'+esc(r.meta||'-')+'</td></tr>';
  });
  if(!recentLogs.length) h+='<tr><td colspan="4" style="text-align:center;color:var(--tx3);padding:18px">Belum ada aktivitas terbaru.</td></tr>';
  h+='</tbody></table></div></div>';
  h+='<div style="display:flex;flex-direction:column;gap:12px">';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><div style="font-size:13px;font-weight:800;color:var(--tx)">Supplier Prioritas</div><button class="btns" onclick="_navTo(\'finance\');setTimeout(function(){_renderFinance(\'hutang\')},60)" style="width:auto">Hutang</button></div>';
  supplierTop.forEach(function(r){ h+='<div style="background:var(--bg3);border:1px solid var(--bd);border-left:2px solid #FFD68A;border-radius:8px;padding:10px;margin-bottom:8px"><div style="display:flex;justify-content:space-between;gap:10px"><div><div style="font-size:12px;font-weight:800;color:var(--tx)">'+esc(r.nama)+'</div><div style="font-size:10px;color:var(--tx2);margin-top:3px">Nota Rp '+fmt(r.nota)+' • Bayar Rp '+fmt(r.bayar)+'</div></div><div style="font-size:11px;font-weight:800;color:#FFD68A">Rp '+fmt(r.saldo)+'</div></div></div>'; });
  if(!supplierTop.length) h+='<div style="color:var(--tx3);text-align:center;padding:14px 10px">Belum ada hutang supplier aktif.</div>';
  h+='</div>';
  h+='<div class="card" style="margin-bottom:0;padding:12px"><div style="font-size:13px;font-weight:800;color:var(--tx);margin-bottom:10px">Akses Cepat</div><div style="display:flex;gap:6px;flex-wrap:wrap">';
  [['HR Desk','_navTo(\'hr\')','#1565C0'],['Penilaian','_navTo(\'hr\');setTimeout(function(){_renderHR(\'eval\')},60)','#00838F'],['Payroll','_navTo(\'hr\');setTimeout(function(){_renderHR(\'payroll\')},60)','#0F9D58'],['Pendapatan','_navTo(\'finance\');setTimeout(function(){_renderFinance(\'income\')},60)','#C27C2C'],['Pengeluaran','_navTo(\'finance\');setTimeout(function(){_renderFinance(\'expense\')},60)','#C62828'],['Laporan Bulanan','_navTo(\'finance\');setTimeout(function(){_renderFinance(\'lapbul\')},60)','#6A1B9A'],['Tools','_navTo(\'tools\')','#546E7A'],['Admin','_navTo(\'admin\')','#374151']].forEach(function(btn){ h+='<button class="btnp" onclick="'+btn[1]+'" style="background:'+btn[2]+';padding:7px 11px;font-size:11px">'+btn[0]+'</button>'; });
  h+='</div></div></div></div>';
  document.getElementById('V-dash').innerHTML=h;
}
